# Generated by Django 6.0.4 on 2026-04-28 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', 'livro_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='dono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livro',
            name='tipo',
            field=models.CharField(choices=[('capa_mole', 'Capa Mole'), ('capa_dura', 'Capa Dura'), ('bolso', 'Livro de Bolso'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
    ]
