# Generated by Django 6.0.4 on 2026-04-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_livro_ano_livro_dono_livro_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='dono',
            new_name='proprietario',
        ),
    ]
