# Generated by Django 6.0.4 on 2026-04-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_rename_dono_livro_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
