# Generated by Django 6.0.4 on 2026-05-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livro_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='email_contacto',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
